### ISSUE TITLE
error: file 'nur-jomik' was not found in the Nix search path 

### ISSUE THREAD

**Issue by LinArcX** [Jomik/dotfiles#1]
Hi. i use your config files(some parts of it), and when i want to switch to new generation:
home-manager switch 

```
error: file 'nur-jomik' was not found in the Nix search path (add it using $NIX_PATH or -I), at /home/linarcx/.config/nixpkgs/home.nix:22:29
(use '--show-trace' to show detailed location information)

There are 3 unread and relevant news items.
Read them by running the command 'home-manager news'.
```

My config files:
https://github.com/LinArcX/Blogit/tree/master/OS/NixOs/Config/home-manager/nixpkgs

**Comment by Jomik** [comment]
I recently switched to use a channel to handle updating my nur. So you will have to add this, if you want to do the same:
`nix-channel --add https://gitlab.com/Jomik/nur-expressions/-/archive/master/nur-expressions-master.tar.gz nur-jomik`
Alternatively you can just fetch it either with a specific rev, or just master.
https://github.com/Jomik/dotfiles/commit/d6acab181b81b36aa7c0d1ca99437d9ef3709fad

**Comment by LinArcX** [comment]
Thank you so much. Actually after adding that channel, user must update the channel:
`nix-channel --update nur-jomik`
And then:
`home-manager switch`
