### ISSUE TITLE
Cannot show other blocks of i3blocks

### ISSUE THREAD

**Issue by LinArcX** [Jomik/dotfiles#2]
Hi again. when i rebuild the configurations, only time block show to me and another blocks doesn't appear on i3blocks. why?

**Comment by Jomik** [comment]
Are you restarting i3 after it has been rebuilt?

**Comment by LinArcX** [comment]
@Jomik  Yes.

**Comment by Jomik** [comment]
That feels very odd.
Try to dump the contents of `~/.config/i3blocks/config`.
Also check debug output with   `statusCommand = "2> /tmp/i3blocks.err ${i3blocks}/bin/i3blocks -vvv | tee /tmp/i3blocks.out";`
You can use `tail -f /tmp/i3blocks.{out,err}`

**Comment by LinArcX** [comment]
The output of: `~/.config/i3blocks/config`:
https://gist.github.com/LinArcX/30379e0bd899dec4e17b41c3e2cd8254

The output of `tail -f /tmp/i3blocks.{out,err}`:
https://gist.github.com/LinArcX/64037b8a53db3abad27c24b0305c6fb4

Also i can't run for example:
`/nix/store/2vvpphs0jsyc4qwa7vapc6hmzpa0va5a-battery`
It require sudo and after i run it with sudo;
`sudo: /nix/store/2vvpphs0jsyc4qwa7vapc6hmzpa0va5a-battery: command not found`

**Comment by Jomik** [comment]
Are they executable?
The debug output indicates they aren't :D

`chmod +x ~/.config/nixpkgs/configurations/i3/{battery,battery_draw,brightness,cpu,memory,ssid,volume}` does it for me.

**Comment by LinArcX** [comment]
Yes, indeed, they now works as expected. thank you.
