### ISSUE TITLE
Error: Duplicate keybinding in config file

### ISSUE THREAD

**Issue by LinArcX** [Jomik/dotfiles#3]
If i add this line:
```
"${modifier} + Return" = "exec kitty";
```
or even:
"${modifier} + Return" = "exec i3-sensible-terminal";

to:
```
keybindings = with pkgs; with nur.repos.jomik; mkOptionDefault {  }
```
part in i3(default.nix) file and restart the i3,  i get this error:
```
Error: Duplicate keybinding in config file:
state mask 0x40 with keysystem Return, command "exec i3-sensible-terminal"
```
```

**Comment by LinArcX** [comment]
Ok , this issues is fixed too :
Just replace:
`keybindings = with pkgs; with nur.repos.jomik; mkOptionDefault {}`
With:
`keybindings = with pkgs; mkOptionDefault { }`

**Comment by Jomik** [comment]
Very odd! I don't really see how having my nur repo there should influence it. Guess you could look at the generated config file.
I've had no issues overriding keybindings at least :)
