### ISSUE TITLE
How to change font size in blocks?

### ISSUE THREAD

**Issue by LinArcX** [Jomik/dotfiles#4]
Hi. i add a new block like this:

```
#!/usr/bin/env bash

function bar {
  date=$1
  width=${BAR_WIDTH:-20}
  echo -n "<span rise='500' color='$TEXT_COLOR'>"
  echo -en "<span><font size='6'>$1</font></span>"
  echo "</span>"
}

date=$(jdate +%D'*'%G)

bar $date
```
As you can see i wrap the result text into: `<font size='6'>` but it won't show in bar. why?

**Comment by Jomik** [comment]
Is markup set to pango?

**Comment by Jomik** [comment]
Sorry, your span should look like
`<span font=6>$1<\span>`

**Comment by LinArcX** [comment]
> Is markup set to pango?

Yes.

**Comment by LinArcX** [comment]
> Sorry, your span should look like
> `<span font=6>$1<\span>`

It works. thank you.

**Comment by Jomik** [comment]
Great :) also, this probably fits better in https://github.com/vivien/i3blocks if you have any further issues with i3blocks
