### ISSUE TITLE
Reduce gap between blocks.

### ISSUE THREAD

**Issue by LinArcX** [Jomik/dotfiles#5]
Hi. right now everything is ok. but the gap between blocks is too long. i want to reduce it. but i don't know how. look:
https://gist.githubusercontent.com/LinArcX/d9cfe069273c5b0b92139be321ec0aef/raw/4742e28cf96302cf8fc0cf2b9fec85dd4fc96732/sc.png

**Comment by Jomik** [comment]
Please post your i3blocks related issues on their github https://github.com/vivien/i3blocks :wink:
